[package]
authors = ["hoggetaylor <hoggetaylor@gmail.com>"]
name = "stego_js_demo"
version = "0.1.0"

[dependencies]
rand = "0.3.16"
stdweb = "0.1.1"
url = "1.5.1"

[dependencies.matrix_code]
path = "../stego/matrix_code"
